---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: "{{ my_namespace }}"
  labels:
    app: express
spec:
  replicas: "{{ app_nr_of_replicas }}"
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: "{{ app_container_name }}"
        image: iulia1234/getting-started
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: todos
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: secret
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
            
---
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: "{{ namespace }}"
spec:
  selector:
    app: express
  ports:
  - protocol: TCP
    port: 3000
