---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: "{{ namespace }}"
  labels:
    app: mysql
spec:
  replicas: "{{ db_nr_of_replicas }}"
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: "{{mysql_container_name}}"
        image: mysql:8.0.34
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: todos
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: secret
        ports:
        -  containerPort: 3306
        resources:
          requests:
            memory: 500Mi
            cpu: 350m
          limits:
            memory: 550Mi
            cpu: 500m
            
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: "{{ namespace }}"
spec:
  selector:
    app: mysql
  ports:
  -  port: 3300
     targetPort: 3306

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-claim-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
---
